### ISSUE TITLE
flatpak support

### ISSUE THREAD

**Issue by ghost** [MaurycyLiebner/enve#18]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by MaurycyLiebner** [comment]
I have no preference when it comes to Flatpack/AppImage.
I just happen to release enve as an AppImage. Why use both?

**Comment by DontUseGithub** [comment]
More discoverability? Flatpak has a nice, popular repo - flathub.org which people use to find new apps. Having enve be part of it could result in more people discovering it.

**Comment by arcooke** [comment]
I actually came here to see if anyone had requested snap/flatpak support.  I use all 3 somewhat regularly, and I've grown to prefer snaps and flatpaks over appimages.  A few reasons for that:

* The snapcraft and flathub stores are convenient and nice to use, as long as the maintainers keep their packages updated. And as @DontUseGithub mentioned, there's a benefit of discoverability. 
* Support for snaps and flatpaks is integrated into a lot of package managers, so all updates come from the same place at the same time.  Appimages either self-update or don't update at all, and need to be replaced manually.. which is inconsistent/annoying, respectively.
* I don't like how appimages ask to integrate themselves into the system on first run, but provide no mechanism un-integrate them after you delete the software.. requiring you to manually delete any orphaned files (.desktop files and whatever else).

I prefer snaps over both due to the support for release channels.  Stable/beta/edge/etc.  That's a handy feature.  Depending on the software, I sometimes prefer newer over more stable, or vice versa.

In my view, appimages are better suited for software that benefits from portability, whereas snaps and flatpaks seem to make more sense for permanent installations.

This isn't really a request.. I have plenty of ways to run your software. Just adding my two cents.  🙂

**Comment by ZanderBrown** [comment]
> I prefer snaps over both due to the support for release channels. Stable/beta/edge/etc.

flatpak can do that as well! gnome apps publish nightly branches on gnome-nightly and many apps on flathub now use flathub-beta

Personally I prefer flatpak to snap on the basis they work on distros other than Ubuntu (don't let Canonical fool you) and are sandboxed by default

**Comment by eszlari** [comment]
For flatpak, the app needs to be able to be built without internet connect. Looking at the build instructions, this seems not to be the case with skia:

> Synchronize the skia dependencies:
> 
> python tools/git-sync-deps

Also, can skia really only be compiled with `g++-7`?

**Comment by eszlari** [comment]
@MaurycyLiebner I have opened a PR on Flathub. If you are interessted in having commit access to a future repo, please comment.

**Comment by MaurycyLiebner** [comment]
`Also, can skia really only be compiled with g++-7?`
I couldn't get skia to compile with g++-5, not sure whether it is still the case.
I think Skia can be compiled with clang++-5. I am currently using clang++-7 for CI builds.

**Comment by MaurycyLiebner** [comment]
> @MaurycyLiebner I have opened a PR on Flathub. If you are interested in having commit access to a future repo, please comment.

Thank you, I know nothing about Flatpak, couldn't have done it myself.

**Comment by eszlari** [comment]
> `Also, can skia really only be compiled with g++-7?`
> I couldn't get skia to compile with g++-5, not sure whether it is still the case.
> I think Skia can be compiled with clang++-5. I am currently using clang++-7 for CI builds.

Forget that comment from me, Flatpak provides gcc-9 and clang-8, no problem there. I thought from your compile instruction, that you needed an older version specifically.

**Comment by eszlari** [comment]
Btw: You can easily test the Flatpak build locally:

```
$ sudo apt install flatpak-builder
$ flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak install --user flathub org.kde.Sdk//5.14
$ git clone --branch=enve --recurse-submodules  https://github.com/eszlari/flathub.git
$ cd flathub
$ flatpak-builder --user --ccache --install --force-clean build_dir io.github.maurycyliebner.enve.yaml
$ flatpak run io.github.maurycyliebner.enve
```

**Comment by eszlari** [comment]
enve is now available on Flathub: :tada:

https://flathub.org/apps/details/io.github.maurycyliebner.enve

**Comment by MaurycyLiebner** [comment]
@eszlari thank you for single-handedly making this happen.
