### ISSUE TITLE
Enve Error pop ups on *.ev file opening... then crash... 

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#49]
Enve Error pop ups on *.ev file opening... then crash... Looks like the *.ev file might have got corrupted...

See video and source file *.ev in zip archive...

[Enve-crash-plus-source-file.zip](https://github.com/MaurycyLiebner/enve/files/4017889/Enve-crash-plus-source-file.zip)

**Comment by MaurycyLiebner** [comment]
Backwards compatibility is not guaranteed. The file you save with the current version of enve might not work with the future version. Usually I will try to keep things backward compatible when adding new things, but when removing / replacing features it would clutter the code fairly quickly to do so, and with enve being in early stages of development, it would not make sense.

I checked the file you uploaded, and the issue is probably related to changes in the way Text Objects work.

The compatibility breaking changes should not happen often, and I will try to stop them altogether in the nearest future.

**Comment by dadoprom** [comment]
ok, no problemo  :+1:
