### ISSUE TITLE
Scaled up ungrouped object is not following the cursor while moving...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#50]
Reproduce the issue:

1. create few objects
2. group them
3. scale up the group - make it bigger
4. ungroup
6. try to move one object - you will experience the object not to follow the cursor while moving the object... moving the single objects is weird

This does not happen to unscaled ungrouped objects...

See attached video...

[enve-video-moving-objects.zip](https://github.com/MaurycyLiebner/enve/files/4020677/enve-video-moving-objects.zip)

**Comment by MaurycyLiebner** [comment]
Thank you for reporting these issues. The more issues I fix, the better enve gets.

**Comment by dadoprom** [comment]
Yes, thats what I am trying to do... it is really fantastic application! Great job man!

**Comment by MaurycyLiebner** [comment]
That's a new bug, introduced when working on Text Effects. A one-liner.

**Comment by dadoprom** [comment]
Ok it is not fixed... 

1. scale up the grouped object
2. ungroup ...
... and the ungrouped objects shrinks back to the size before scaling...

...so, now the issue with object not following the cursor dissapeared but... it can not even happen now :)

**Comment by MaurycyLiebner** [comment]
When you remove an object from its parenting group, it no longer inherits the transformation of the group.

The transformation cannot be saved, because transformation for every object is defined in local coordinates, and keeping parenting group's transformation would require it to be stored as a matrix, and that would make no sense for animatable transformation.

The only situation where the transformation could be kept is a Group containing only Path Objects, where either the Group's transformation is static, or all Path Objects' paths are static. Here the transformation would be applied to children's paths, not to children's transformation. It cannot be done for any other object in any other situation, so it would be inconsistent to do so for the special case.

**Comment by dadoprom** [comment]
Oh, ok, I understand your explanation...
