### ISSUE TITLE
Width of stroke on selected objects is not changing evenly...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#56]
Width of stroke on selected objects is not changing evenly...

Reproduce issue:

1. write letters "ac"
2. SCALE UP (without this the issue does not appear)
3. convert text to path
4. Break appart
5. select both objects at "a" and click "Difference"
6. select newly created path "a" and unchanged "c" and try to change the width of stroke - it is not changing evenly on both objects...

See attached video in zip (it all happens at the end of the video)...

[enve-stroke-width.zip](https://github.com/MaurycyLiebner/enve/files/4022671/enve-stroke-width.zip)

**Comment by MaurycyLiebner** [comment]
The stroke width is affected by the Object's transformation.
When you scale an Object the stroke width is also affected.

The Objects that are the result of operations will have no transformation (and scale equal to 1), because they are created by combining two Objects, that can have different transformations.

The difference in the stroke width is a result of the scale difference of Objects.
If you want a Path Object to have scale equal to 1, while retaining it's size, you can reset the scale (Alt + S), and then scale all path nodes.

There is also "Apply Transformation" in the context menu, but it does not work right now, I will fix it.

**Comment by dadoprom** [comment]
Oh, ok, makes sense... this should be than writen in a FAQ or manual or something like that...
