### ISSUE TITLE
Ungroup will make object change position and orientation

### ISSUE THREAD

**Issue by gromain** [MaurycyLiebner/enve#63]
Hi!

I just started using your software so I may fill up a bit of bug reports!
I'm running the latest AppImage, version 343919f.
So when I import a SVG file, and ungroup it, it gets mirrored upside down. If I group it and mirror it again so it's in the right orientation, if I ungroup it again, it again gets mirrored upside down.

I'm not sure where this is coming from. I can do more debug if you tell me how.

**Comment by MaurycyLiebner** [comment]
The problem is that parenting Group's transformation cannot be applied to Objects with animated transformation, without making a complete mess. It could be applied only to static Objects by the means of matrix decomposition.

Maybe there should be an option to "Ungroup (keep transformation)" for Group Objects containing only static Objects, which should be the default behaviour for Alt + G shortcut. It would be a bit inconsistent, though.
