### ISSUE TITLE
Missing api-ms-win-core-libraryloader-l1-2-1.dll in W8

### ISSUE THREAD

**Issue by dinilu** [MaurycyLiebner/enve#94]
I just found out about enve (very excited about it). I tried to install both windows builds (4_4_20 and 4_5_20) with the same result: it installs but when launchin Enve it doesn't start with System Error that the api-ms-win-core-libraryloader-l1-2-1.dll is missing. It suggest to reinstall the app, but this doesn't help.
Let me know if/how I can help fixing the issue.

**Comment by MaurycyLiebner** [comment]
I build enve using Windows 10, there are probably some libraries missing from W8 that are present in W10. I will try to resolve the issue with the next release.

**Comment by MaurycyLiebner** [comment]
Please try 4/6/20, I do not have W8 so I cannot test it myself.

**Comment by dinilu** [comment]
Still giving the same error. Is there anything I can do to help debug it?

**Comment by MaurycyLiebner** [comment]
The problem is that these dependencies are part of Windows itself, and shipping them with enve is not the way to go. I am currently using VS2017, I will try using VS2015 some time in the future to see whether that would help. All you have to do is test whether it works. I am not an avid Windows user so please bare with me.

**Comment by Jose-Moreno** [comment]
@dinilu Try installing or repairing (if you previously installed) this redistributable and see if the missing file gets installed for you, the ones form the following page are the most udpated ones and include a baseline universal c runtime.
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

If this specific installation does not work, leave it installed and try to install the other files for vc_redist 2017 and 2015 (the links inside the site redirect to microsoft, no worries)

https://www.itechtics.com/microsoft-visual-c-redistributable-versions-direct-download-links/

Since the specific dll files are part of the Windows 10 SDK, it's possible only 2017 and 2019 redists can add them to your system, but it might not be a complete solution so If that doesn't work you might need to wait for enve2d to sort out this issue.

---

@MaurycyLiebner There is a note included in the first link above which might interest you:
> **Note** Visual C++ 2015, 2017 and 2019 all share the same redistributable files.

> For example, installing the Visual C++ 2019 redistributable will affect programs built with Visual C++ 2015 and 2017 also. However, installing the Visual C++ 2015 redistributable will not replace the newer versions of the files installed by the Visual C++ 2017 and 2019 redistributables.

> This is different from all previous Visual C++ versions, as they each had their own distinct runtime files, not shared with other versions.

https://social.msdn.microsoft.com/Forums/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls
This forum reply (where the OP missing .dll is mentioned) state that Microsoft has been moving these dll files between versions, so you probably might not need to downgrade to VS 2015, but aside from that it suggests to try the following from a development perspective:

> If you are a developer, just use the APIs documented in the Windows SDK (unless absolute necessary like writing antivirus) and do not take any dependency on those dlls, as they may only exist in one Windows version. 
> Those APIs may or may not use the DLLs you listed, but their dependencies are not yours to worry. You should only depend on documented APIs, not implementation details like the name of those DLL. E.g. instead of taking a direct dependency on api-ms-win-core-file-l1-2-0.dll you should take a dependency on kernel.dll which supports Windows 7 as well. 

Lastly this is a list for the win32 APIs where reported dll is shown
https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis

And it seems the specific functions the missing file links, come from `libloaderapi.h` and are supported all the way back to Windows XP.

**Comment by dinilu** [comment]
Thank you @Jose-Moreno for all the detailed information. I want to confirm that none of the suggested solutions has fixed the issue. I understand that developing and fixing for W8 is not a priority and I can install Enve in W10 in the computer at work where I will mostly use it.

**Comment by MaurycyLiebner** [comment]
You can try the 4/7/20 release. I added some LLVM DLLs.

You do not have to worry about making a mess with all the enve installs.
When you uninstall enve it leaves no trace behind.

**Comment by dinilu** [comment]
Justr tried, but still missing the library.

**Comment by MaurycyLiebner** [comment]
I am afraid I do not know how to make it work. Maybe someone with relevant experience will come forward.

**Comment by dinilu** [comment]
Thanks for trying several times! Hopefully someone else can point you in the right direction.

**Comment by MaurycyLiebner** [comment]
Good news, I think I know how to fix the issue. I have to use Windows SDK that supports W8, I was using Windows 10 SDK. I will try that in couple of days.

**Comment by dinilu** [comment]
That's awesome! Let me know when you have done the migration and I can try again to confirm that was in the right direction.

**Comment by MaurycyLiebner** [comment]
I successfully ran enve 4/14/20 on Windows 7.

**Comment by dinilu** [comment]
I can confirm that last windows version 4/27/20 is working on Windows 8. Thank you for taking the time to fix this! :) Keep with the good work!
